### ISSUE TITLE
Armor Stand Editor との連携でエラーが起こって起動しない

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/StandLock#13]
Armor Stand Editorとの連携部分で、エラーが起こって起動していない。

<pre>
[21:54:14] [Server thread/INFO]: [StandLock] Enabling StandLock v1.2.0
[21:54:14] [Server thread/ERROR]: Error occurred while enabling StandLock v1.2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: io/github/rypofalem/armorstandeditor/protection/ASEProtection
   at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
   at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51]
   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_51]
   at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_51]
   at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_51]
   at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_51]
   at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_51]
   at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_51]
   at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_51]
   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:191) ~[spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
   at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
   at org.bitbucket.ucchy.sl.StandLock.onEnable(StandLock.java:71) ~[?:?]
   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: io.github.rypofalem.armorstandeditor.protection.ASEProtection
   at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51]
   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.2_3.jar:git-Spigot-7d78b81-775f1e1]
   at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
   at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
   ... 27 more
</pre>

**Comment by ucchyocean** [comment]
仕方がないので、Armor Stand Editorとの連携はいったん削除するしかない。
Armor Stand Editorが、正式に連携I/Fを作成したら対応できるが、それまではPendingとする。

**Comment by ucchyocean** [comment]
b4a8d0aa7cf8a75698b194b796fdcb269b540cdd

**Comment by ucchyocean** [comment]
Fixed
動作確認OK
